files = [
  "tru_wbgen2_pkg.vhd",  
  "wrsw_tru_pkg.vhd",
  "xwrsw_tru.vhd",
  "wrsw_tru_wb.vhd",
  "tru_port.vhd",
  "tru_reconfig_rt_port_handler.vhd",
  "tru_sub_vlan_pattern.vhd",
  "tru_wishbone_slave.vhd",
  "tru_endpoint.vhd",
  "tru_transition.vhd",
  "tru_trans_marker_trig.vhd",
  "tru_trans_lacp_dist.vhd",
  "tru_trans_lacp_colect.vhd",
  ]
